
package ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BankReleveWs", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BankReleveWs {


    /**
     * 
     * @return
     *     returns java.util.List<ws.Operation>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "operationList", targetNamespace = "http://ws/", className = "ws.OperationList")
    @ResponseWrapper(localName = "operationListResponse", targetNamespace = "http://ws/", className = "ws.OperationListResponse")
    @Action(input = "http://ws/BankReleveWs/operationListRequest", output = "http://ws/BankReleveWs/operationListResponse")
    public List<Operation> operationList();

    /**
     * 
     * @param rib
     * @return
     *     returns ws.Releve
     */
    @WebMethod(operationName = "BankStatement")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "BankStatement", targetNamespace = "http://ws/", className = "ws.BankStatement")
    @ResponseWrapper(localName = "BankStatementResponse", targetNamespace = "http://ws/", className = "ws.BankStatementResponse")
    @Action(input = "http://ws/BankReleveWs/BankStatementRequest", output = "http://ws/BankReleveWs/BankStatementResponse")
    public Releve bankStatement(
        @WebParam(name = "RIB", targetNamespace = "")
        int rib);

}
