
package ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Relevebanque", targetNamespace = "http://ws/", wsdlLocation = "http://192.168.1.101:8080/Relevebanque?wsdl")
public class Relevebanque
    extends Service
{

    private final static URL RELEVEBANQUE_WSDL_LOCATION;
    private final static WebServiceException RELEVEBANQUE_EXCEPTION;
    private final static QName RELEVEBANQUE_QNAME = new QName("http://ws/", "Relevebanque");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.1.101:8080/Relevebanque?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RELEVEBANQUE_WSDL_LOCATION = url;
        RELEVEBANQUE_EXCEPTION = e;
    }

    public Relevebanque() {
        super(__getWsdlLocation(), RELEVEBANQUE_QNAME);
    }

    public Relevebanque(WebServiceFeature... features) {
        super(__getWsdlLocation(), RELEVEBANQUE_QNAME, features);
    }

    public Relevebanque(URL wsdlLocation) {
        super(wsdlLocation, RELEVEBANQUE_QNAME);
    }

    public Relevebanque(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RELEVEBANQUE_QNAME, features);
    }

    public Relevebanque(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Relevebanque(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BankReleveWs
     */
    @WebEndpoint(name = "BankReleveWsPort")
    public BankReleveWs getBankReleveWsPort() {
        return super.getPort(new QName("http://ws/", "BankReleveWsPort"), BankReleveWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BankReleveWs
     */
    @WebEndpoint(name = "BankReleveWsPort")
    public BankReleveWs getBankReleveWsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws/", "BankReleveWsPort"), BankReleveWs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RELEVEBANQUE_EXCEPTION!= null) {
            throw RELEVEBANQUE_EXCEPTION;
        }
        return RELEVEBANQUE_WSDL_LOCATION;
    }

}
